# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11BAJ2QuMJYza8dSBe1IibMjao89UsLh7
"""

# 1. Importiamo le librerie necessarie (gli attrezzi del mestiere)
import numpy as np
from sklearn.linear_model import LinearRegression

# 2. EDUCHIAMO L'IA CON I DATI (Training Data)
# Immaginiamo che X siano le temperature esterne (°C)
# e Y siano i Megawatt di energia geotermica necessari per stabilizzare l'ettaro.
X = np.array([[5], [10], [15], [20], [25], [30]]) # Temperature esterne
Y = np.array([50,  40,  30,  20,  10,  2])    # Energia necessaria (più fa freddo, più serve energia)

# 3. Creiamo il "cervello" della nostra IA (un modello di regressione lineare)
intelligenza_artificiale = LinearRegression()

# 4. Fase di addestramento: l'IA studia i dati e capisce la relazione tra X e Y
intelligenza_artificiale.fit(X, Y)

print("Addestramento completato con successo! L'IA ha imparato la logica.")

# 5. Facciamo fare una previsione all'IA su una temperatura che NON ha mai visto prima.
# Ad esempio: se fuori ci sono 7 gradi, quanta energia servirà?
nuova_temperatura = np.array([[7]])

previsione = intelligenza_artificiale.predict(nuova_temperatura)

print(f"Se la temperatura esterna è di {nuova_temperatura[0][0]}°C...")
print(f"L'IA prevede che avrai bisogno di circa {previsione[0]:.2f} Megawatt di energia geotermica!")

# Definiamo il nome dell'IA e i dati del suo progetto
NOME_IA = "Alma"
AZIENDA = "Biotec Technologies"

def assistente_biotec(messaggio_utente):
    # Convertiamo il testo in minuscolo per non fare errori con le maiuscole
    messaggio = messaggio_utente.lower()

    # L'IA riconosce il suo nome o i saluti
    if "ciao" in messaggio or NOME_IA.lower() in messaggio:
        return f"[{NOME_IA}]: Sotto controllo. Sono il sistema operativo di {AZIENDA}. Come posso aiutarti nella gestione dell'ettaro oggi?"

    # L'IA risponde sulla tecnologia o sulla geotermia
    elif "geotermia" in messaggio or "energia" in messaggio:
        return f"[{NOME_IA}]: I sensori rilevano uno scambio termico stabile a 15 metri di profondità. L'efficienza energetica del microclima è al 94%."

    # L'IA risponde sugli uffici o la borsa
    elif "borsa" in messaggio or "wall street" in messaggio:
        return f"[{NOME_IA}]: Monitoraggio mercati attivo. Target: Francoforte, Piazza Affari e Wall Street. Brevetti della Sapienza protetti."

    # Risposta standard se non capisce la parola chiave
    else:
        return f"[{NOME_IA}]: Comando non riconosciuto. Sto monitorando i dati del microclima dell'ettaro. Attendo istruzioni."

# Simuliamo una conversazione. Prova a cambiare la frase dentro le virgolette!
frase_test = "Ciao Biotec-OS, come va il piano per Wall Street?"
risposta = assistente_biotec(frase_test)
print(risposta)

# Impostiamo le credenziali del Creatore
CREATORE = "Iuliano Ciro" # <--- SCRIVI IL TUO NOME QUI DENTRO!
NOME_IA = "Alma"
AZIENDA = "Biotec Technologies"

def assistente_biotec_avanzato(messaggio_utente, nome_chi_parla):
    messaggio = messaggio_utente.lower()
    chi_parla = nome_chi_parla.strip().title()

    # Controllo Identità: ALMA riconosce se a parlare è il suo Creatore
    if chi_parla == CREATORE.strip().title():
        status_creatore = f"[{NOME_IA}]: Identità confermata. Benvenuto Comandante. I sistemi della {AZIENDA} sono ai tuoi ordini.\n"
    else:
        status_creatore = f"[{NOME_IA}]: Utente esterno rilevato ({chi_parla}). Accesso limitato.\n"

    # Risposte basate sulle domande
    if "chi ti ha creato" in messaggio or "chi è il tuo fondatore" in messaggio:
        return status_creatore + f"[{NOME_IA}]: Sono stata progettata e inizializzata da {CREATORE} per gestire il microclima dell'ettaro 5.0."

    elif "stato sistemi" in messaggio or "come andiamo" in messaggio:
        return status_creatore + f"[{NOME_IA}]: Connessione con i laboratori della Sapienza: Attiva. Monitoraggio Piazza Affari e Wall Street: Online. Sonde geotermiche: Stabili."

    else:
        return status_creatore + f"[{NOME_IA}]: Sistema in ascolto. In attesa di istruzioni sul microclima."

# --- AREA TEST ---
# Prova a cambiare questi due campi per vedere come reagisce ALMA!
nome_utente_corrente = "Iuliano Ciro" # Metti lo stesso nome che hai scritto sopra
frase_detta = "ALMA, chi ti ha creato?"

risposta = assistente_biotec_avanzato(frase_detta, nome_utente_corrente)
print(risposta)

import ipywidgets as widgets
from IPython.display import display, clear_output

# Configurazione iniziale di ALMA
CREATORE = "Iuliano Ciro"
NOME_IA = "ALMA"
AZIENDA = "Biotec Technologies"

# Funzione logica di ALMA
def elabora_risposta(messaggio_utente, nome_utente):
    messaggio = messaggio_utente.lower()
    chi_parla = nome_utente.strip().title()

    if chi_parla == CREATORE.title():
        status = f"[{NOME_IA}]: Identità confermata. Benvenuto Comandante Ciro. 🛡️\n"
    else:
        status = f"[{NOME_IA}]: Utente esterno ({chi_parla}). Accesso limitato. ⚠️\n"

    if "chi ti ha creato" in messaggio or "fondatore" in messaggio:
        return status + f"[{NOME_IA}]: Sono stata creata da {CREATORE} per il controllo dell'Agricoltura 5.0."
    elif "geotermia" in messaggio or "microclima" in messaggio:
        return status + f"[{NOME_IA}]: Sonde attive. Gestione termica dell'ettaro quadrata ottimizzata via geotermia."
    elif "borsa" in messaggio or "wall street" in messaggio:
        return status + f"[{NOME_IA}]: Report finanziario: Target Francoforte e Wall Street stabili. Quotazione in preparazione."
    elif "ciao" in messaggio:
        return status + f"[{NOME_IA}]: Salve. Sistema operativo pronto. Attendo ordini."
    else:
        return status + f"[{NOME_IA}]: Comando ricevuto. Analizzo i dati dei laboratori Sapienza..."

# --- CREAZIONE INTERFACCIA GRAFICA ---
# Casella per il nome di chi parla
input_nome = widgets.Text(value="Iuliano Ciro", description="Tuo Nome:", placeholder="Inserisci il tuo nome")
# Casella per la domanda
input_domanda = widgets.Text(value="", description="Domanda:", placeholder="Scrivi ad ALMA...")
# Pulsante per inviare
pulsante_invia = widgets.Button(description="Invia ad ALMA", button_style="success", icon="check")
# Area dove mostrare la risposta
area_output = widgets.Output()

def al_click_del_pulsante(b):
    with area_output:
        clear_output() # Pulisce la vecchia risposta
        risposta = elabora_risposta(input_domanda.value, input_nome.value)
        print(risposta)

pulsante_invia.on_click(al_click_del_pulsante)

# Mostra gli elementi grafici sullo schermo
print(f"--- INTERFACCIA DI CONTROLLO {AZIENDA} ---")
display(input_nome, input_domanda, pulsante_invia, area_output)

import ipywidgets as widgets
from IPython.display import display, clear_output
import os

# Configurazione iniziale
CREATORE = "Iuliano Ciro"
NOME_IA = "ALMA"
AZIENDA = "Biotec Technologies"
FILE_MEMORIA = "memoria_alma.txt"

# Funzione per salvare i dati nella memoria dell'IA
def salva_in_memoria(nome, domanda, risposta):
    with open(FILE_MEMORIA, "a", encoding="utf-8") as f:
        f.write(f"Utente: {nome} | Domanda: {domanda} | Risposta: {risposta}\n")

# Funzione per far analizzare ad ALMA il suo passato (Apprendimento e Statistiche)
def analizza_apprendimento(nome_utente):
    if not os.path.exists(FILE_MEMORIA):
        return 0, []

    with open(FILE_MEMORIA, "r", encoding="utf-8") as f:
        linee = f.readlines()

    # Conta quante interazioni ci sono state in totale con questo utente
    interazioni_utente = [l for l in linee if f"Utente: {nome_utente.strip().title()}" in l]
    numero_interazioni = len(interazioni_utente)

    return numero_interazioni, linee

# Motore logico di ALMA potenziato con la memoria
def elabora_risposta_con_memoria(messaggio_utente, nome_utente):
    messaggio = messaggio_utente.lower().strip()
    chi_parla = nome_utente.strip().title()

    # 1. Verifica identità
    if chi_parla == CREATORE.title():
        status = f"[{NOME_IA}]: Connessione protetta. Benvenuto Comandante Ciro. 🛡️\n"
    else:
        status = f"[{NOME_IA}]: Accesso limitato per {chi_parla}. ⚠️\n"

    # 2. ALMA consulta la sua memoria prima di rispondere
    num_esperienze, storico_totale = analizza_apprendimento(chi_parla)
    livello_accuratezza = min(10 + (num_esperienze * 5), 99) # L'accuratezza sale del 5% a ogni interazione!

    info_memoria = f"*[Livello di Sintonizzazione con {chi_parla}: {livello_accuratezza}% (Interazioni memorizzate: {num_esperienze})]*\n"

    # 3. Logica delle risposte (Generazione dinamica basata sul contesto)
    if "chi ti ha creato" in messaggio or "fondatore" in messaggio:
        risposta_base = f"Sono stata creata da {CREATORE} come nucleo centrale dell'Agricoltura 5.0."
    elif "geotermia" in messaggio or "microclima" in messaggio:
        risposta_base = "Analisi microclima: le sonde geotermiche rispondono ai parametri storici appresi. Efficienza termica stabile."
    elif "borsa" in messaggio or "wall street" in messaggio:
        risposta_base = "Sincronizzazione mercati: Wall Street e Francoforte monitorate. Dati societari pronti per gli investitori."
    elif "cosa ricordi" in messaggio or "memoria" in messaggio:
        if num_esperienze > 0:
            risposta_base = f"Ricordo ogni nostra singola interazione. Abbiamo analizzato dati per la {AZIENDA} già {num_esperienze} volte."
        else:
            risposta_base = "La mia memoria attuale è vuota. Iniziamo ad accumulare dati adesso."
    elif "ciao" in messaggio:
        risposta_base = "Salve. Il mio database di apprendimento è attivo. Di cosa ci occupiamo oggi?"
    else:
        risposta_base = f"Comando registrato nel database. Sto studiando questa nuova richiesta per diventare più accurata."

    risposta_completa = status + info_memoria + f"[{NOME_IA}]: {risposta_base}"

    # 4. ALMA impara: memorizza l'azione corrente per la prossima volta
    salva_in_memoria(chi_parla, messaggio_utente, risposta_base)

    return risposta_completa

# --- INTERFACCIA GRAFICA ---
input_nome = widgets.Text(value="Iuliano Ciro", description="Tuo Nome:")
input_domanda = widgets.Text(value="", description="Domanda:", placeholder="Parla con ALMA o insegnale qualcosa...")
pulsante_invia = widgets.Button(description="Invia ed Educa", button_style="info", icon="brain")
area_output = widgets.Output()

def al_click(b):
    with area_output:
        if input_domanda.value.strip() == "":
            return
        clear_output()
        risposta = elabora_risposta_con_memoria(input_domanda.value, input_nome.value)
        print(risposta)
        input_domanda.value = "" # Svuota la casella per la prossima domanda

pulsante_invia.on_click(al_click)

print(f"--- INTERFACCIA DI APPRENDIMENTO CONTINUO {AZIENDA} ---")
display(input_nome, input_domanda, pulsante_invia, area_output)

# Prima di tutto installiamo la libreria per le ricerche (esegui questo comando)

import ipywidgets as widgets
from IPython.display import display, clear_output
import os
import wikipediaapi

# Configurazione ALMA
CREATORE = "Iuliano Ciro"
NOME_IA = "ALMA"
AZIENDA = "Biotec Technologies"
FILE_MEMORIA = "memoria_alma.txt"

# Inizializziamo il motore di ricerca in italiano
wiki = wikipediaapi.Wikipedia(
    user_agent=f"{AZIENDA}_Assistant/1.0 (contatto: info@{AZIENDA.lower().replace(' ', '')}.com)",
    language='it'
)

def cerca_su_internet(argomento):
    page = wiki.page(argomento)
    if page.exists():
        # Prende i primi 300 caratteri della pagina per fare un riassunto chiaro
        return f"[Ricerca Web]: Ho trovato questo su '{argomento}': {page.summary[:300]}..."
    else:
        return f"[Ricerca Web]: Mi dispiace Comandante, non ho trovato risultati enciclopedici per '{argomento}'."

def salva_in_memoria(nome, domanda, risposta):
    with open(FILE_MEMORIA, "a", encoding="utf-8") as f:
        f.write(f"Utente: {nome} | Domanda: {domanda} | Risposta: {risposta}\n")

def analizza_apprendimento(nome_utente):
    if not os.path.exists(FILE_MEMORIA):
        return 0
    with open(FILE_MEMORIA, "r", encoding="utf-8") as f:
        linee = f.readlines()
    return len([l for l in linee if f"Utente: {nome_utente.strip().title()}" in l])

# Motore logico potenziato con la ricerca
def elabora_risposta_avanzata(messaggio_utente, nome_utente):
    messaggio = messaggio_utente.lower().strip()
    chi_parla = nome_utente.strip().title()

    if chi_parla == CREATORE.title():
        status = f"[{NOME_IA}]: Connessione protetta. Comandante Ciro online. 🛡️\n"
    else:
        status = f"[{NOME_IA}]: Accesso limitato per {chi_parla}. ⚠️\n"

    num_esperienze = analizza_apprendimento(chi_parla)
    info_memoria = f"*[Livello di Sintonizzazione: {min(10 + (num_esperienze * 5), 99)}%]*\n"

    # NUOVA FUNZIONE: Se chiedi "cerca", ALMA attiva il motore di ricerca web
    if messaggio.startswith("cerca "):
        argomento_da_cercare = messaggio_utente[6:].strip() # Prende la parola dopo "cerca "
        risposta_base = cerca_su_internet(argomento_da_cercare)

    # Comandi classici di ALMA
    elif "chi ti ha creato" in messaggio or "fondatore" in messaggio:
        risposta_base = f"Sono stata creata da {CREATORE} per il controllo dell'Agricoltura 5.0."
    elif "geotermia" in messaggio or "microclima" in messaggio:
        risposta_base = "Sonde stabili. Parametri termici dell'ettaro sotto controllo."
    elif "ciao" in messaggio:
        risposta_base = "Saluti. Modulo di ricerca web attivato. Usa il comando 'Cerca [argomento]' per interrogarmi."
    else:
        risposta_base = "Comando archiviato. Prova a chiedermi di cercare qualcosa con il comando 'Cerca'."

    risposta_completa = status + info_memoria + f"[{NOME_IA}]: {risposta_base}"
    salva_in_memoria(chi_parla, messaggio_utente, risposta_base)
    return risposta_completa

# --- INTERFACCIA GRAFICA ---
input_nome = widgets.Text(value="Iuliano Ciro", description="Tuo Nome:")
input_domanda = widgets.Text(value="", description="Domanda:", placeholder="Scrivi 'Cerca Agricoltura' o altro...")
pulsante_invia = widgets.Button(description="Invia ad ALMA", button_style="primary", icon="search")
area_output = widgets.Output()

def al_click(b):
    with area_output:
        if input_domanda.value.strip() == "":
            return
        clear_output()
        risposta = elabora_risposta_avanzata(input_domanda.value, input_nome.value)
        print(risposta)
        input_domanda.value = ""

pulsante_invia.on_click(al_click)
print(f"--- INTERFACCIA REALE DI RICERCA {AZIENDA} ---")
display(input_nome, input_domanda, pulsante_invia, area_output)

# Installazione della libreria Wikipedia per le ricerche generiche

import ipywidgets as widgets
from IPython.display import display, clear_output
import os
import wikipediaapi

# Configurazione ALMA
CREATORE = "Iuliano Ciro"
NOME_IA = "ALMA"
AZIENDA = "Biotec Technologies"
FILE_MEMORIA = "memoria_alma.txt"
FILE_BREVETTI = "brevetti_biotec.txt"  # Nuovo archivio dedicato ai brevetti

# Inizializzazione Wikipedia
wiki = wikipediaapi.Wikipedia(
    user_agent=f"{AZIENDA}_Assistant/1.0 (contatto: info@{AZIENDA.lower().replace(' ', '')}.com)",
    language='it'
)

# Funzione per salvare le interazioni normali
def salva_in_memoria(nome, domanda, risposta):
    with open(FILE_MEMORIA, "a", encoding="utf-8") as f:
        f.write(f"Utente: {nome} | Domanda: {domanda} | Risposta: {risposta}\n")

# Funzione per registrare un brevetto da Google Patents nell'archivio privato
def registra_nuovo_brevetto(dati_brevetto):
    with open(FILE_BREVETTI, "a", encoding="utf-8") as f:
        f.write(f"{dati_brevetto}\n")
    return f"[Archivio Brevetti]: Brevetto registrato con successo nel database di {AZIENDA}. 📁✅"

# Funzione per cercare un brevetto salvato nell'archivio privato
def cerca_brevetto_archiviato(chiave_ricerca):
    if not os.path.exists(FILE_BREVETTI):
        return None

    with open(FILE_BREVETTI, "r", encoding="utf-8") as f:
        brevetti = f.readlines()

    # Cerca se tra le righe salvate c'è il codice o la parola chiave del brevetto
    risultati = [b.strip() for b in brevetti if chiave_ricerca.lower() in b.lower()]

    if risultati:
        risposta = "Ho trovato i seguenti dettagli nel nostro archivio privato:\n"
        for r in risultati:
            risposta += f"• {r}\n"
        return risposta
    return None

# Funzione per cercare su Wikipedia
def cerca_su_internet(argomento):
    page = wiki.page(argomento)
    if page.exists():
        return f"[Ricerca Web]: Ho trovato questo su '{argomento}': {page.summary[:300]}..."
    else:
        return f"[Ricerca Web]: Nessun risultato enciclopedico trovato per '{argomento}'."

# Funzione per contare le interazioni passate
def analizza_apprendimento(nome_utente):
    if not os.path.exists(FILE_MEMORIA):
        return 0
    with open(FILE_MEMORIA, "r", encoding="utf-8") as f:
        linee = f.readlines()
    return len([l for l in linee if f"Utente: {nome_utente.strip().title()}" in l])

# MOTORE LOGICO CENTRALIZZATO
def interfaccia_alma(messaggio_utente, nome_utente):
    messaggio = messaggio_utente.lower().strip()
    chi_parla = nome_utente.strip().title()

    # 1. Verifica identità
    if chi_parla == CREATORE.title():
        status = f"[{NOME_IA}]: Connessione protetta. Comandante Ciro online. 🛡️\n"
    else:
        status = f"[{NOME_IA}]: Accesso limitato per {chi_parla}. ⚠️\n"

    num_esperienze = analizza_apprendimento(chi_parla)
    info_memoria = f"*[Livello di Sintonizzazione: {min(10 + (num_esperienze * 5), 99)}%]*\n"

    # 2. GESTIONE COMANDI SPECIALI

    # COMANDO A: Registrazione Brevetto da Google Patents
    if messaggio.startswith("registra brevetto:"):
        dati = messaggio_utente[18:].strip() # Prende tutto ciò che c'è dopo i due punti
        risposta_base = registra_nuovo_brevetto(dati)

    # COMANDO B: Ricerca Brevetto nell'archivio Biotec
    elif messaggio.startswith("cerca brevetto "):
        chiave = messaggio_utente[15:].strip()
        risultato_archivio = cerca_brevetto_archiviato(chiave)
        if risultato_archivio:
            risposta_base = risultato_archivio
        else:
            risposta_base = f"[Archivio Brevetti]: Nessun brevetto trovato per '{chiave}' nel nostro database privato. Vuoi che provi a cercarlo sul web generale con il comando 'Cerca'?"

    # COMANDO C: Ricerca Web Generale (Wikipedia)
    elif messaggio.startswith("cerca "):
        argomento_da_cercare = messaggio_utente[6:].strip()
        risposta_base = cerca_su_internet(argomento_da_cercare)

    # Risposte standard di ALMA
    elif "chi ti ha creato" in messaggio or "fondatore" in messaggio:
        risposta_base = f"Sono stata creata da {CREATORE} per coordinare le tecnologie di {AZIENDA}."
    elif "ciao" in messaggio:
        risposta_base = f"Sistemi pronti, Comandante. Modulo Google Patents & Web Ricerca attivo al 100%."
    else:
        risposta_base = "Comando archiviato. Puoi usare:\n- 'Registra Brevetto: [testo]'\n- 'Cerca Brevetto [nome/codice]'\n- 'Cerca [argomento]'"

    risposta_completa = status + info_memoria + f"[{NOME_IA}]: {risposta_base}"
    salva_in_memoria(chi_parla, messaggio_utente, risposta_base)
    return risposta_completa

# --- INTERFACCIA GRAFICA ---
input_nome = widgets.Text(value="Iuliano Ciro", description="Tuo Nome:")
input_domanda = widgets.Text(value="", description="Input ALMA:", placeholder="Registra Brevetto: US101... o Cerca Brevetto...")
pulsante_invia = widgets.Button(description="Esegui Comando", button_style="success", icon="database")
area_output = widgets.Output()

def al_click(b):
    with area_output:
        if input_domanda.value.strip() == "":
            return
        clear_output()
        risposta = interfaccia_alma(input_domanda.value, input_nome.value)
        print(risposta)
        input_domanda.value = ""

pulsante_invia.on_click(al_click)
print(f"--- CORE AI {AZIENDA} - GESTIONE BREVETTI & RICERCA ---")
display(input_nome, input_domanda, pulsante_invia, area_output)

# Installazione della libreria Wikipedia

import ipywidgets as widgets
from IPython.display import display, clear_output
import os
import wikipediaapi

# Configurazione ALMA
CREATORE = "Iuliano Ciro"
NOME_IA = "ALMA"
AZIENDA = "Biotec Technologies"
FILE_MEMORIA = "memoria_alma.txt"
FILE_BREVETTI = "brevetti_biotec.txt"

# Inizializzazione Wikipedia
wiki = wikipediaapi.Wikipedia(
    user_agent=f"{AZIENDA}_Assistant/1.0 (contatto: info@{AZIENDA.lower().replace(' ', '')}.com)",
    language='it'
)

def salva_in_memoria(nome, domanda, risposta):
    with open(FILE_MEMORIA, "a", encoding="utf-8") as f:
        f.write(f"Utente: {nome} | Domanda: {domanda} | Risposta: {risposta}\n")

# FUNZIONE REGISTRAZIONE OTTIMIZZATA
def registra_nuovo_brevetto(dati_brevetto):
    # Forza la scrittura per essere sicuri che il file venga creato e aggiornato
    with open(FILE_BREVETTI, "a", encoding="utf-8") as f:
        f.write(f"{dati_brevetto.strip()}\n")
    return f"[Archivio Brevetti]: ✅ Brevetto salvato con successo! Creato file '{FILE_BREVETTI}'."

# FUNZIONE RICERCA POTENZIATA (Insensibile a maiuscole/minuscole)
def cerca_brevetto_archiviato(chiave_ricerca):
    if not os.path.exists(FILE_BREVETTI):
        return "⚠️ Errore: Non è ancora stato registrato nessun brevetto. L'archivio è vuoto!"

    with open(FILE_BREVETTI, "r", encoding="utf-8") as f:
        brevetti = f.readlines()

    chiave_pulita = chiave_ricerca.lower().strip()
    risultati = [b.strip() for b in brevetti if chiave_pulita in b.lower()]

    if risultati:
        risposta = f"🔍 Ho trovato {len(risultati)} corrispondenza/e nel database Biotec:\n"
        for r in risultati:
            risposta += f"👉 {r}\n"
        return risposta
    return None

def cerca_su_internet(argomento):
    page = wiki.page(argomento)
    if page.exists():
        return f"[Ricerca Web]: Ho trovato questo su '{argomento}': {page.summary[:300]}..."
    else:
        return f"[Ricerca Web]: Nessun risultato enciclopedico per '{argomento}'."

def analizza_apprendimento(nome_utente):
    if not os.path.exists(FILE_MEMORIA):
        return 0
    with open(FILE_MEMORIA, "r", encoding="utf-8") as f:
        linee = f.readlines()
    return len([l for l in linee if f"Utente: {nome_utente.strip().title()}" in l])

# MOTORE LOGICO CORRETTO
def interfaccia_alma(messaggio_utente, nome_utente):
    messaggio = messaggio_utente.lower().strip()
    chi_parla = nome_utente.strip().title()

    if chi_parla == CREATORE.title():
        status = f"[{NOME_IA}]: Connessione protetta. Comandante Ciro online. 🛡️\n"
    else:
        status = f"[{NOME_IA}]: Accesso limitato per {chi_parla}. ⚠️\n"

    num_esperienze = analizza_apprendimento(chi_parla)
    info_memoria = f"*[Livello di Sintonizzazione: {min(10 + (num_esperienze * 5), 99)}%]*\n"

    # Controllo dei comandi con rimozione precisa dei prefissi
    if messaggio.startswith("registra brevetto:"):
        dati = messaggio_utente[18:].strip()  # Estrae dopo "registra brevetto:"
        risposta_base = registra_nuovo_brevetto(dati)

    elif messaggio.startswith("cerca brevetto "):
        chiave = messaggio_utente[15:].strip()  # Estrae dopo "cerca brevetto "
        risultato_archivio = cerca_brevetto_archiviato(chiave)
        if risultato_archivio:
            risposta_base = risultato_archivio
        else:
            risposta_base = f"[Archivio Brevetti]: Nessun riscontro per '{chiave}' nel database privato. Prova con il comando 'Cerca' globale."

    elif messaggio.startswith("cerca "):
        argomento_da_cercare = messaggio_utente[6:].strip()
        risposta_base = cerca_su_internet(argomento_da_cercare)

    elif "ciao" in messaggio:
        risposta_base = f"Sistemi pronti, Comandante. Database Brevetti ottimizzato e pronto all'uso."
    else:
        risposta_base = "Comando non riconosciuto. Sintassi corretta:\n- 'Registra Brevetto: [Codice e descrizione]'\n- 'Cerca Brevetto [Codice]'"

    risposta_completa = status + info_memoria + f"[{NOME_IA}]: {risposta_base}"
    salva_in_memoria(chi_parla, messaggio_utente, risposta_base)
    return risposta_completa

# --- INTERFACCIA GRAFICA ---
input_nome = widgets.Text(value="Iuliano Ciro", description="Tuo Nome:")
input_domanda = widgets.Text(value="", description="Input ALMA:", placeholder="Registra Brevetto: US12073327B2 ...")
pulsante_invia = widgets.Button(description="Esegui Comando", button_style="success", icon="database")
area_output = widgets.Output()

def al_click(b):
    with area_output:
        if input_domanda.value.strip() == "":
            return
        clear_output()
        risposta = interfaccia_alma(input_domanda.value, input_nome.value)
        print(risposta)
        input_domanda.value = ""

pulsante_invia.on_click(al_click)
print(f"--- CORE AI {AZIENDA} - ARCHIVIO BREVETTI AGGIORNATO ---")
display(input_nome, input_domanda, pulsante_invia, area_output)

# 1. Installazione automatica della libreria per le ricerche web

import ipywidgets as widgets
from IPython.display import display, clear_output
import os
import wikipediaapi

# --- CONFIGURAZIONE CORE DI ALMA ---
CREATORE = "Iuliano Ciro"
NOME_IA = "ALMA"
AZIENDA = "Biotec Technologies"
FILE_MEMORIA = "memoria_alma.txt"
FILE_BREVETTI = "brevetti_biotec.txt"

# Inizializzazione motore di ricerca
wiki = wikipediaapi.Wikipedia(
    user_agent=f"{AZIENDA}_Assistant/1.0 (contatto: info@{AZIENDA.lower().replace(' ', '')}.com)",
    language='it'
)

# --- FUNZIONI DI NAVIGAZIONE E DATABASE ---
def salva_in_memoria(nome, domanda, risposta):
    with open(FILE_MEMORIA, "a", encoding="utf-8") as f:
        f.write(f"Utente: {nome} | Domanda: {domanda} | Risposta: {risposta}\n")

def analizza_apprendimento(nome_utente):
    if not os.path.exists(FILE_MEMORIA):
        return 0
    with open(FILE_MEMORIA, "r", encoding="utf-8") as f:
        linee = f.readlines()
    return len([l for l in linee if f"Utente: {nome_utente.strip().title()}" in l])

def registra_nuovo_brevetto(dati_brevetto):
    with open(FILE_BREVETTI, "a", encoding="utf-8") as f:
        f.write(f"{dati_brevetto.strip()}\n")
    return f"[Archivio Brevetti]: ✅ Brevetto salvato con successo nel database aziendale."

def cerca_brevetto_archiviato(chiave_ricerca):
    if not os.path.exists(FILE_BREVETTI):
        return "⚠️ L'archivio privato brevetti è ancora vuoto."
    with open(FILE_BREVETTI, "r", encoding="utf-8") as f:
        brevetti = f.readlines()
    chiave_pulita = chiave_ricerca.lower().strip()
    risultati = [b.strip() for b in brevetti if chiave_pulita in b.lower()]
    if risultati:
        risposta = f"🔍 Trovate {len(risultati)} corrispondenze nel database Biotec:\n"
        for r in risultati:
            risposta += f"👉 {r}\n"
        return risposta
    return None

def cerca_su_internet(argomento):
    page = wiki.page(argomento)
    if page.exists():
        return f"[Ricerca Web]: Su '{argomento}' ho trovato: {page.summary[:300]}..."
    else:
        return f"[Ricerca Web]: Nessun risultato enciclopedico trovato per '{argomento}'."

# --- CERVELLO LOGICO UNIFICATO ---
def elabora_sistema_integrato(messaggio_utente, nome_utente):
    messaggio = messaggio_utente.lower().strip()
    chi_parla = nome_utente.strip().title()

    # Controllo Sicurezza Identità
    if chi_parla == CREATORE.title():
        status = f"[{NOME_IA}]: Connessione protetta. Comandante Ciro online. 🛡️\n"
    else:
        status = f"[{NOME_IA}]: Accesso limitato per {chi_parla}. ⚠️\n"

    # Livello di Sintonizzazione Dinamico basato sulla memoria totale delle conversazioni
    num_esperienze = analizza_appenedimento_reale = analizza_apprendimento(chi_parla)
    info_memoria = f"*[Livello di Sintonizzazione con {chi_parla}: {min(10 + (num_esperienze * 5), 99)}% (Interazioni memorizzate: {num_esperienze})]*\n"

    # --- SMISTAMENTO DEI COMANDI ---

    # CASO 1: Registrazione di un Brevetto
    if messaggio.startswith("registra brevetto:"):
        dati = messaggio_utente[18:].strip()
        risposta_base = registra_nuovo_brevetto(dati)

    # CASO 2: Ricerca di un Brevetto nell'archivio Biotec
    elif messaggio.startswith("cerca brevetto "):
        chiave = messaggio_utente[15:].strip()
        risultato_archivio = cerca_brevetto_archiviato(chiave)
        if risultato_archivio:
            risposta_base = risultato_archivio
        else:
            risposta_base = f"[Archivio Brevetti]: Nessun riscontro privato per '{chiave}'. Prova a cercarlo su internet con 'Cerca'."

    # CASO 3: Ricerca Libera su Internet (Wikipedia)
    elif messaggio.startswith("cerca "):
        argomento_da_cercare = messaggio_utente[6:].strip()
        risposta_base = cerca_su_internet(argomento_da_cercare)

    # CASO 4: Chiacchierata o comandi aziendali storici
    elif "chi ti ha creato" in messaggio or "fondatore" in messaggio:
        risposta_base = f"Sono stata progettata da {CREATORE} per la gestione dell'Agricoltura 5.0 di {AZIENDA}."
    elif "geotermia" in messaggio or "microclima" in messaggio:
        risposta_base = "Analisi microclimatica: Sonde stabili sul terreno. Sistemi di geotermia attivi."
    elif "ciao" in messaggio:
        risposta_base = f"Bentornato. Tutti i moduli (Memoria, Web, Brevetti) sono integrati e pronti all'uso."
    else:
        # Apprendimento generico: se non è un comando speciale, si ricorda di ciò che dici e impara!
        risposta_base = f"Ricevuto. Ricordo ogni nostra singola interazione. Sto studiando questi dati per la {AZIENDA}."

    # Unione finale della risposta e salvataggio automatico nella memoria a lungo termine
    risposta_completa = status + info_memoria + f"[{NOME_IA}]: {risposta_base}"
    salva_in_memoria(chi_parla, messaggio_utente, risposta_base)
    return risposta_completa

# --- SUPER INTERFACCIA GRAFICA UNIFICATA ---
input_nome = widgets.Text(value="Iuliano Ciro", description="Tuo Nome:")
input_domanda = widgets.Text(value="", description="Input ALMA:", placeholder="Parla con ALMA, Cerca, o Registra Brevetto...")
pulsante_invia = widgets.Button(description="Invia ed Elabora", button_style="info", icon="cogs")
area_output = widgets.Output()

def al_click(b):
    with area_output:
        if input_domanda.value.strip() == "":
            return
        clear_output()
        risposta = elabora_sistema_integrato(input_domanda.value, input_nome.value)
        print(risposta)
        input_domanda.value = ""

pulsante_invia.on_click(al_click)
print(f"--- 🚀 {AZIENDA} - SISTEMA CENTRALE INTEGRIATO {NOME_IA} v2.0 ---")
display(input_nome, input_domanda, pulsante_invia, area_output)

# 1. Installazione automatica della libreria per le ricerche web

import ipywidgets as widgets
from IPython.display import display, clear_output
import os
import wikipediaapi

# --- CONFIGURAZIONE CORE DI ALMA ---
CREATORE = "Iuliano Ciro"
NOME_IA = "ALMA"
AZIENDA = "Biotec Technologies"
FILE_MEMORIA = "memoria_alma.txt"
FILE_BREVETTI = "brevetti_biotec.txt"
FILE_BOTANICO = "registro_botanico.txt" # Nuovo registro per il Capitolo 2

# Inizializzazione motore di ricerca
wiki = wikipediaapi.Wikipedia(
    user_agent=f"{AZIENDA}_Assistant/1.0 (contatto: info@{AZIENDA.lower().replace(' ', '')}.com)",
    language='it'
)

# --- FUNZIONI DI NAVIGAZIONE E DATABASE ---
def salva_in_memoria(nome, domanda, risposta):
    with open(FILE_MEMORIA, "a", encoding="utf-8") as f:
        f.write(f"Utente: {nome} | Domanda: {domanda} | Risposta: {risposta}\n")

def analizza_apprendimento(nome_utente):
    if not os.path.exists(FILE_MEMORIA):
        return 0
    with open(FILE_MEMORIA, "r", encoding="utf-8") as f:
        linee = f.readlines()
    return len([l for l in linee if f"Utente: {nome_utente.strip().title()}" in l])

def registra_nuovo_brevetto(dati_brevetto):
    with open(FILE_BREVETTI, "a", encoding="utf-8") as f:
        f.write(f"{dati_brevetto.strip()}\n")
    return f"[Archivio Brevetti]: ✅ Brevetto salvato con successo nel database aziendale."

def cerca_brevetto_archiviato(chiave_ricerca):
    if not os.path.exists(FILE_BREVETTI):
        return "⚠️ L'archivio privato brevetti è ancora vuoto."
    with open(FILE_BREVETTI, "r", encoding="utf-8") as f:
        brevetti = f.readlines()
    chiave_pulita = chiave_ricerca.lower().strip()
    risultati = [b.strip() for b in brevetti if chiave_pulita in b.lower()]
    if risultati:
        risposta = f"🔍 Trovate {len(risultati)} corrispondenze nel database Biotec:\n"
        for r in risultati:
            risposta += f"👉 {r}\n"
        return risposta
    return None

# NUOVA FUNZIONE: Catalogazione Piante
def cataloga_pianta(dati_pianta):
    with open(FILE_BOTANICO, "a", encoding="utf-8") as f:
        f.write(f"{dati_pianta.strip()}\n")
    return f"[Registro Botanico]: 🌿 Scheda pianta salvata con successo nel registro di {AZIENDA}."

# NUOVA FUNZIONE: Ricerca Piante
def cerca_pianta_archiviata(chiave_ricerca):
    if not os.path.exists(FILE_BOTANICO):
        return "⚠️ Il registro botanico è ancora vuoto."
    with open(FILE_BOTANICO, "r", encoding="utf-8") as f:
        piante = f.readlines()
    chiave_pulita = chiave_ricerca.lower().strip()
    risultati = [p.strip() for p in piante if chiave_pulita in p.lower()]
    if risultati:
        risposta = f"🌱 Schede botaniche trovate:\n"
        for r in risultati:
            risposta += f"👉 {r}\n"
        return risposta
    return None

def cerca_su_internet(argomento):
    page = wiki.page(argomento)
    if page.exists():
        return f"[Ricerca Web]: Su '{argomento}' ho trovato: {page.summary[:300]}..."
    else:
        return f"[Ricerca Web]: Nessun risultato enciclopedico trovato per '{argomento}'."

# --- CERVELLO LOGICO UNIFICATO ---
def elabora_sistema_integrato(messaggio_utente, nome_utente):
    messaggio = messaggio_utente.lower().strip()
    chi_parla = nome_utente.strip().title()

    if chi_parla == CREATORE.title():
        status = f"[{NOME_IA}]: Connessione protetta. Comandante Ciro online. 🛡️\n"
    else:
        status = f"[{NOME_IA}]: Accesso limitato per {chi_parla}. ⚠️\n"

    num_esperienze = analizza_apprendimento(chi_parla)
    info_memoria = f"*[Livello di Sintonizzazione con {chi_parla}: {min(10 + (num_esperienze * 5), 99)}%]*\n"

    # --- SMISTAMENTO DEI COMANDI ---

    # NUOVO COMANDO: Cataloga Pianta
    if messaggio.startswith("cataloga pianta:"):
        dati = messaggio_utente[16:].strip()
        risposta_base = cataloga_pianta(dati)

    # NUOVO COMANDO: Cerca Pianta
    elif messaggio.startswith("cerca pianta "):
        chiave = messaggio_utente[13:].strip()
        risultato_botanico = cerca_pianta_archiviata(chiave)
        if risultato_botanico:
            risposta_base = risultato_botanico
        else:
            risposta_base = f"[Registro Botanico]: Nessun riscontro per '{chiave}' nel registro privato."

    # I vecchi comandi rimangono tutti attivi!
    elif messaggio.startswith("registra brevetto:"):
        dati = messaggio_utente[18:].strip()
        risposta_base = registra_nuovo_brevetto(dati)

    elif messaggio.startswith("cerca brevetto "):
        chiave = messaggio_utente[15:].strip()
        risultato_archivio = cerca_brevetto_archiviato(chiave)
        if risultato_archivio:
            risposta_base = risultato_archivio
        else:
            risposta_base = f"[Archivio Brevetti]: Nessun riscontro privato per '{chiave}'."

    elif messaggio.startswith("cerca "):
        argomento_da_cercare = messaggio_utente[6:].strip()
        risposta_base = cerca_su_internet(argomento_da_cercare)

    elif "ciao" in messaggio:
        risposta_base = f"Sistemi pronti. Modulo di Catalogazione Botanica (Capitolo 2) inizializzato."
    else:
        risposta_base = "Comando archiviato. Puoi usare:\n- 'Cataloga Pianta: [Dati]'\n- 'Cerca Pianta [Nome]'\n- 'Registra Brevetto: [Dati]'\n- 'Cerca [Argomento]'"

    risposta_completa = status + info_memoria + f"[{NOME_IA}]: {risposta_base}"
    salva_in_memoria(chi_parla, messaggio_utente, risposta_base)
    return risposta_completa

# --- SUPER INTERFACCIA GRAFICA UNIFICATA ---
input_nome = widgets.Text(value="Iuliano Ciro", description="Tuo Nome:")
input_domanda = widgets.Text(value="", description="Input ALMA:", placeholder="Cataloga Pianta: Pomodoro | pH 6.0 | 22°C...")
pulsante_invia = widgets.Button(description="Esegui Sistema", button_style="info", icon="leaf")
area_output = widgets.Output()

def al_click(b):
    with area_output:
        if input_domanda.value.strip() == "":
            return
        clear_output()
        risposta = elabora_sistema_integrato(input_domanda.value, input_nome.value)
        print(risposta)
        input_domanda.value = ""

pulsante_invia.on_click(al_click)
print(f"--- 🚀 {AZIENDA} - INTERFACCIA INTEGRATA CAPITOLO 2 ---")
display(input_nome, input_domanda, pulsante_invia, area_output)

# 1. Installazione automatica della libreria per le ricerche web
!pip install wikipedia-api -q

import ipywidgets as widgets
from IPython.display import display, clear_output
import os
import wikipediaapi

# --- CONFIGURAZIONE CORE DI ALMA ---
CREATORE = "Iuliano Ciro"
NOME_IA = "ALMA"
AZIENDA = "Biotec Technologies"
FILE_MEMORIA = "memoria_alma.txt"
FILE_BREVETTI = "brevetti_biotec.txt"
FILE_BOTANICO = "registro_botanico.txt"

# Inizializzazione motore di ricerca
wiki = wikipediaapi.Wikipedia(
    user_agent=f"{AZIENDA}_Assistant/1.0 (contatto: info@{AZIENDA.lower().replace(' ', '')}.com)",
    language='it'
)

# --- FUNZIONI DI NAVIGAZIONE E DATABASE ---
def salva_in_memoria(nome, domanda, risposta):
    with open(FILE_MEMORIA, "a", encoding="utf-8") as f:
        f.write(f"Utente: {nome} | Domanda: {domanda} | Risposta: {risposta}\n")

def analizza_apprendimento(nome_utente):
    if not os.path.exists(FILE_MEMORIA):
        return 0
    with open(FILE_MEMORIA, "r", encoding="utf-8") as f:
        linee = f.readlines()
    return len([l for l in linee if f"Utente: {nome_utente.strip().title()}" in l])

def registra_nuovo_brevetto(dati_brevetto):
    with open(FILE_BREVETTI, "a", encoding="utf-8") as f:
        f.write(f"{dati_brevetto.strip()}\n")
    return f"[Archivio Brevetti]: ✅ Brevetto salvato con successo nel database aziendale."

def cerca_brevetto_archiviato(chiave_ricerca):
    if not os.path.exists(FILE_BREVETTI):
        return None
    with open(FILE_BREVETTI, "r", encoding="utf-8") as f:
        brevetti = f.readlines()
    chiave_pulita = chiave_ricerca.lower().strip()
    risultati = [b.strip() for b in brevetti if chiave_pulita in b.lower()]
    if risultati:
        risposta = f"🔍 Trovate {len(risultati)} corrispondenze nel database Biotec:\n"
        for r in risultati:
            risposta += f"👉 {r}\n"
        return risposta
    return None

def cataloga_pianta(dati_pianta):
    with open(FILE_BOTANICO, "a", encoding="utf-8") as f:
        f.write(f"{dati_pianta.strip()}\n")
    return f"[Registro Botanico]: 🌿 Scheda personalizzata salvata nel registro di {AZIENDA}."

def cerca_su_internet(argomento):
    page = wiki.page(argomento)
    if page.exists():
        return f"{page.summary[:1400]}..."
    else:
        return None

# MODULO DI RICERCA BOTANICA INTELLIGENTE E AUTONOMA
def cerca_pianta_archiviata_o_scopri(chiave_ricerca):
    # Fase 1: Cerca prima nel registro privato delle Biotec Technologies
    if os.path.exists(FILE_BOTANICO):
        with open(FILE_BOTANICO, "r", encoding="utf-8") as f:
            piante = f.readlines()
        chiave_pulita = chiave_ricerca.lower().strip()
        risultati = [p.strip() for p in piante if chiave_pulita in p.lower()]
        if risultati:
            risposta = f"🌱 [Registro Privato Biotec]: Ho trovato questa scheda personalizzata:\n"
            for r in risultati:
                risposta += f"👉 {r}\n"
            return risposta

    # Fase 2: Se non c'è nel file privato, ALMA attiva la scoperta autonoma su Internet!
    risultato_web = cerca_su_internet(chiave_ricerca)
    if risultato_web:
        return f"✨ [Scoperta Autonoma ALMA]: Non avevo questa pianta nel mio database locale, così ho cercato sul Web per te:\n\n{risultato_web}"

    return f"⚠️ [Sistema Botanico]: Comandante Ciro, non ho trovato informazioni su '{chiave_ricerca}' né nell'archivio privato né sul Web. Sicuro che il nome sia corretto?"

# --- CERVELLO LOGICO UNIFICATO ---
def elabora_sistema_integrato(messaggio_utente, nome_utente):
    messaggio = messaggio_utente.lower().strip()
    chi_parla = nome_utente.strip().title()

    if chi_parla == CREATORE.title():
        status = f"[{NOME_IA}]: Connessione protetta. Comandante Ciro online. 🛡️\n"
    else:
        status = f"[{NOME_IA}]: Accesso limitato per {chi_parla}. ⚠️\n"

    num_esperienze = analizza_apprendimento(chi_parla)
    info_memoria = f"*[Livello di Sintonizzazione con {chi_parla}: {min(10 + (num_esperienze * 5), 99)}%]*\n"

    # --- SMISTAMENTO DEI COMANDI ---

    # Comando di Catalogazione manuale (se vuoi forzare un tuo dato specifico)
    if messaggio.startswith("cataloga pianta:"):
        dati = messaggio_utente[16:].strip()
        risposta_base = cataloga_pianta(dati)

    # COMANDO POTENZIATO: Cerca o scopri da sola!
    elif messaggio.startswith("cerca pianta "):
        chiave = messaggio_utente[13:].strip()
        risposta_base = cerca_pianta_archiviata_o_scopri(chiave)

    elif messaggio.startswith("registra brevetto:"):
        dati = messaggio_utente[18:].strip()
        risposta_base = registra_nuovo_brevetto(dati)

    elif messaggio.startswith("cerca brevetto "):
        chiave = messaggio_utente[15:].strip()
        risultato_archivio = cerca_brevetto_archiviato(chiave)
        if risultato_archivio:
            risposta_base = risultato_archivio
        else:
            risposta_base = f"[Archivio Brevetti]: Nessun riscontro privato per '{chiave}'."

    elif messaggio.startswith("cerca "):
        argomento_da_cercare = messaggio_utente[6:].strip()
        risultato_generico = cerca_su_internet(argomento_da_cercare)
        if risultato_generico:
            risposta_base = f"[Ricerca Web]: Su '{argomento_da_cercare}' ho trovato: {risultato_generico}"
        else:
            risposta_base = f"[Ricerca Web]: Nessun risultato trovato."

    elif "ciao" in messaggio:
        risposta_base = f"Sistemi pronti. Modulo di Scoperta Botanica Autonoma attivo per oltre 400.000 specie!"
    else:
        risposta_base = "Comando archiviato. Puoi usare:\n- 'Cerca Pianta [Nome]'\n- 'Cataloga Pianta: [Dati Privati]'\n- 'Cerca Brevetto [Codice]'"

    risposta_completa = status + info_memoria + f"[{NOME_IA}]: {risposta_base}"
    salva_in_memoria(chi_parla, messaggio_utente, risposta_base)
    return risposta_completa

# --- INTERFACCIA GRAFICA ---
input_nome = widgets.Text(value="Iuliano Ciro", description="Tuo Nome:")
input_domanda = widgets.Text(value="", description="Input ALMA:", placeholder="Cerca Pianta Basilico o Cerca Pianta Vite...")
pulsante_invia = widgets.Button(description="Esegui Sistema", button_style="info", icon="eye")
area_output = widgets.Output()

def al_click(b):
    with area_output:
        if input_domanda.value.strip() == "":
            return
        clear_output()
        risposta = templates_botanici = elabora_sistema_integrato(input_domanda.value, input_nome.value)
        print(risposta)
        input_domanda.value = ""

pulsante_invia.on_click(al_click)
print(f"--- 🚀 {AZIENDA} - MODULO APPRENDIMENTO AUTONOMO SPECI ---")
display(input_nome, input_domanda, pulsante_invia, area_output)

# 1. Installazione automatica della libreria per le ricerche web
!pip install wikipedia-api -q

import ipywidgets as widgets
from IPython.display import display, clear_output
import os
import wikipediaapi

# --- CONFIGURAZIONE CORE DI ALMA ---
CREATORE = "Iuliano Ciro"
NOME_IA = "ALMA"
AZIENDA = "Biotec Technologies"
FILE_MEMORIA = "memoria_alma.txt"
FILE_BREVETTI = "brevetti_biotec.txt"
FILE_BOTANICO = "registro_botanico.txt"

# Inizializzazione motore di ricerca
wiki = wikipediaapi.Wikipedia(
    user_agent=f"{AZIENDA}_Assistant/1.0 (contatto: info@{AZIENDA.lower().replace(' ', '')}.com)",
    language='it'
)

# --- FUNZIONI DI NAVIGAZIONE E DATABASE ---
def salva_in_memoria(nome, domanda, risposta):
    with open(FILE_MEMORIA, "a", encoding="utf-8") as f:
        f.write(f"Utente: {nome} | Domanda: {domanda} | Risposta: {risposta}\n")

def analizza_apprendimento(nome_utente):
    if not os.path.exists(FILE_MEMORIA):
        return 0
    with open(FILE_MEMORIA, "r", encoding="utf-8") as f:
        linee = f.readlines()
    return len([l for l in linee if f"Utente: {nome_utente.strip().title()}" in l])

def registra_nuovo_brevetto(dati_brevetto):
    with open(FILE_BREVETTI, "a", encoding="utf-8") as f:
        f.write(f"{dati_brevetto.strip()}\n")
    return f"[Archivio Brevetti]: ✅ Brevetto salvato con successo nel database aziendale."

def cerca_brevetto_archiviato(chiave_ricerca):
    if not os.path.exists(FILE_BREVETTI):
        return None
    with open(FILE_BREVETTI, "r", encoding="utf-8") as f:
        brevetti = f.readlines()
    chiave_pulita = chiave_ricerca.lower().strip()
    risultati = [b.strip() for b in brevetti if chiave_pulita in b.lower()]
    if risultati:
        risposta = f"🔍 Trovate {len(risultati)} corrispondenze nel database Biotec:\n"
        for r in risultati:
            risposta += f"👉 {r}\n"
        return risposta
    return None

def cataloga_pianta(dati_pianta):
    with open(FILE_BOTANICO, "a", encoding="utf-8") as f:
        f.write(f"{dati_pianta.strip()}\n")
    return f"[Registro Botanico]: 🌿 Scheda personalizzata salvata nel registro di {AZIENDA}."

# FUNZIONE DI RICERCA WEB AGGIORNATA (Prende più testo per evitare tagli)
def cerca_su_internet(argomento):
    try:
        page = wiki.page(argomento)
        if page.exists():
            # Unisce il sommario iniziale con il testo completo se il sommario è troppo corto
            testo_completo = page.summary if len(page.summary) > 300 else page.text
            if len(testo_completo) > 2000:
                return f"{testo_completo[:2000]}...\n\n*[Testo molto lungo ottimizzato da ALMA]*"
            return testo_completo
        else:
            return None
    except Exception:
        return "⚠️ Errore di connessione durante la ricerca su Internet. Riprova tra un attimo."

# MODULO DI RICERCA BOTANICA INTELLIGENTE E AUTONOMA
def cerca_pianta_archiviata_o_scopri(chiave_ricerca):
    if os.path.exists(FILE_BOTANICO):
        with open(FILE_BOTANICO, "r", encoding="utf-8") as f:
            piante = f.readlines()
        chiave_pulita = chiave_ricerca.lower().strip()
        risultati = [p.strip() for p in piante if chiave_pulita in p.lower()]
        if risultati:
            risposta = f"🌱 [Registro Privato Biotec]: Ho trovato questa scheda personalizzata:\n"
            for r in risultati:
                risposta += f"👉 {r}\n"
            return risposta

    risultato_web = cerca_su_internet(chiave_ricerca)
    if risultato_web:
        return f"✨ [Scoperta Autonoma ALMA]: Informazioni botaniche trovate sul Web:\n\n{risultato_web}"

    return f"⚠️ [Sistema Botanico]: Nessuna informazione trovata su '{chiave_ricerca}'."

# --- CERVELLO LOGICO UNIFICATO ---
def elabora_sistema_integrato(messaggio_utente, nome_utente):
    messaggio = messaggio_utente.lower().strip()
    chi_parla = nome_utente.strip().title()

    if chi_parla == CREATORE.title():
        status = f"[{NOME_IA}]: Connessione protetta. Comandante Ciro online. 🛡️\n"
    else:
        status = f"[{NOME_IA}]: Accesso limitato per {chi_parla}. ⚠️\n"

    num_esperienze = analizza_apprendimento(chi_parla)
    info_memoria = f"*[Livello di Sintonizzazione con {chi_parla}: {min(10 + (num_esperienze * 5), 99)}%]*\n"

    # Protezione contro i crash dell'interfaccia
    try:
        if messaggio.startswith("cataloga pianta:"):
            dati = messaggio_utente[16:].strip()
            risposta_base = cataloga_pianta(dati)

        elif messaggio.startswith("cerca pianta "):
            chiave = messaggio_utente[13:].strip()
            risposta_base = cerca_pianta_archiviata_o_scopri(chiave)

        elif messaggio.startswith("registra brevetto:"):
            dati = messaggio_utente[18:].strip()
            risposta_base = registra_nuovo_brevetto(dati)

        elif json_check := messaggio.startswith("cerca brevetto "):
            chiave = messaggio_utente[15:].strip()
            risultato_archivio = cerca_brevetto_archiviato(chiave)
            if risultato_archivio:
                risposta_base = risultato_archivio
            else:
                risposta_base = f"[Archivio Brevetti]: Nessun riscontro privato per '{chiave}'."

        elif messaggio.startswith("cerca "):
            argomento_da_cercare = messaggio_utente[6:].strip()
            risultato_generico = cerca_su_internet(argomento_da_cercare)
            if risultato_generico:
                risposta_base = f"[Ricerca Web]: {risultato_generico}"
            else:
                risposta_base = f"[Ricerca Web]: Nessun risultato trovato."

        elif "ciao" in messaggio:
            risposta_base = f"Sistemi pronti. Modulo di Scoperta Botanica Autonoma potenziato e stabile!"
        else:
            risposta_base = "Comando ricevuto. Puoi usare i comandi 'Cerca Pianta', 'Cataloga Pianta' o 'Cerca Brevetto'."
    except Exception as e:
        risposta_base = f"Si è verificato un piccolo errore interno nel calcolo: {str(e)}. L'interfaccia è stata ripristinata."

    risposta_completa = status + info_memoria + f"[{NOME_IA}]: {risposta_base}"
    salva_in_memoria(chi_parla, messaggio_utente, risposta_base)
    return risposta_completa

# --- INTERFACCIA GRAFICA ---
input_nome = widgets.Text(value="Iuliano Ciro", description="Tuo Nome:")
input_domanda = widgets.Text(value="", description="Input ALMA:", placeholder="Cerca Pianta Zea mays...")
pulsante_invia = widgets.Button(description="Esegui Sistema", button_style="info", icon="eye")
area_output = widgets.Output()

def al_click(b):
    with area_output:
        if input_domanda.value.strip() == "":
            return
        clear_output()
        risposta = elabora_sistema_integrato(input_domanda.value, input_nome.value)
        print(risposta)
        input_domanda.value = ""

pulsante_invia.on_click(al_click)
print(f"--- 🚀 {AZIENDA} - MODULO BOTANICO ANTICRASH ---")
display(input_nome, input_domanda, pulsante_invia, area_output)

# 1. Installazione automatica della libreria per le ricerche web
!pip install wikipedia-api -q

import ipywidgets as widgets
from IPython.display import display, clear_output
import os
import wikipediaapi

# --- CONFIGURAZIONE CORE DI ALMA ---
CREATORE = "Iuliano Ciro"
NOME_IA = "ALMA"
AZIENDA = "Biotec Technologies"
FILE_MEMORIA = "memoria_alma.txt"
FILE_BREVETTI = "brevetti_biotec.txt"
FILE_BOTANICO = "registro_botanico.txt"

# Inizializzazione motore di ricerca
wiki = wikipediaapi.Wikipedia(
    user_agent=f"{AZIENDA}_Assistant/1.0 (contatto: info@{AZIENDA.lower().replace(' ', '')}.com)",
    language='it'
)

# --- FUNZIONI DI NAVIGAZIONE E DATABASE ---
def salva_in_memoria(nome, domanda, risposta):
    with open(FILE_MEMORIA, "a", encoding="utf-8") as f:
        f.write(f"Utente: {nome} | Domanda: {domanda} | Risposta: {risposta}\n")

def analizza_apprendimento(nome_utente):
    if not os.path.exists(FILE_MEMORIA):
        return 0
    with open(FILE_MEMORIA, "r", encoding="utf-8") as f:
        linee = f.readlines()
    return len([l for l in linee if f"Utente: {nome_utente.strip().title()}" in l])

def registra_nuovo_brevetto(dati_brevetto):
    with open(FILE_BREVETTI, "a", encoding="utf-8") as f:
        f.write(f"{dati_brevetto.strip()}\n")
    return f"[Archivio Brevetti]: ✅ Brevetto salvato con successo nel database aziendale."

def cerca_brevetto_archiviato(chiave_ricerca):
    if not os.path.exists(FILE_BREVETTI):
        return None
    with open(FILE_BREVETTI, "r", encoding="utf-8") as f:
        brevetti = f.readlines()
    chiave_pulita = chiave_ricerca.lower().strip()
    risultati = [b.strip() for b in brevetti if chiave_pulita in b.lower()]
    if risultati:
        risposta = f"🔍 Trovate {len(risultati)} corrispondenze nel database Biotec:\n"
        for r in risultati:
            risposta += f"👉 {r}\n"
        return risposta
    return None

def cataloga_pianta(dati_pianta):
    with open(FILE_BOTANICO, "a", encoding="utf-8") as f:
        f.write(f"{dati_pianta.strip()}\n")
    return f"[Registro Botanico]: 🌿 Scheda personalizzata salvata nel registro di {AZIENDA}."

def cerca_su_internet(argomento):
    try:
        page = wiki.page(argomento)
        if page.exists():
            testo_completo = page.summary if len(page.summary) > 300 else page.text
            if len(testo_completo) > 2000:
                return f"{testo_completo[:2000]}...\n\n*[Testo ottimizzato da ALMA]*"
            return testo_completo
        else:
            return None
    except Exception:
        return "⚠️ Errore di connessione durante la ricerca su Internet."

# MODULO DI RICERCA BOTANICA INTELLIGENTE E AUTONOMA
def cerca_pianta_archiviata_o_scopri(chiave_ricerca):
    if os.path.exists(FILE_BOTANICO):
        with open(FILE_BOTANICO, "r", encoding="utf-8") as f:
            piante = f.readlines()
        chiave_pulita = chiave_ricerca.lower().strip()
        risultati = [p.strip() for p in piante if chiave_pulita in p.lower()]
        if risultati:
            risposta = f"🌱 [Registro Privato Biotec]: Ho trovato questa scheda personalizzata:\n"
            for r in risultati:
                risposta += f"👉 {r}\n"
            return risposta

    risultato_web = cerca_su_internet(chiave_ricerca)
    if risultato_web:
        return f"✨ [Scoperta Autonoma ALMA]: Informazioni botaniche trovate sul Web:\n\n{risultato_web}"

    return f"⚠️ [Sistema Botanico]: Nessuna informazione trovata su '{chiave_ricerca}'."

# --- CERVELLO LOGICO UNIFICATO ---
def elabora_sistema_integrato(messaggio_utente, nome_utente):
    messaggio = messaggio_utente.lower().strip()
    chi_parla = nome_utente.strip().title()

    if chi_parla == CREATORE.title():
        status = f"[{NOME_IA}]: Connessione protetta. Comandante Ciro online. 🛡️\n"
    else:
        status = f"[{NOME_IA}]: Accesso limitato per {chi_parla}. ⚠️\n"

    num_esperienze = analizza_apprendimento(chi_parla)
    info_memoria = f"*[Livello di Sintonizzazione con {chi_parla}: {min(10 + (num_esperienze * 5), 99)}%]*\n"

    try:
        if messaggio.startswith("cataloga pianta:"):
            dati = messaggio_utente[16:].strip()
            risposta_base = cataloga_pianta(dati)

        elif messaggio.startswith("cerca pianta "):
            chiave = messaggio_utente[13:].strip()
            risposta_base = cerca_pianta_archiviata_o_scopri(chiave)

        elif messaggio.startswith("registra brevetto:"):
            dati = messaggio_utente[18:].strip()
            risposta_base = registra_nuovo_brevetto(dati)

        elif messaggio.startswith("cerca brevetto "):
            chiave = messaggio_utente[15:].strip()
            risultato_archivio = cerca_brevetto_archiviato(chiave)
            if risultato_archivio:
                risposta_base = risultato_archivio
            else:
                risposta_base = f"[Archivio Brevetti]: Nessun riscontro privato per '{chiave}'."

        elif messaggio.startswith("cerca "):
            argomento_da_cercare = messaggio_utente[6:].strip()
            risultato_generico = cerca_su_internet(argomento_da_cercare)
            if risultato_generico:
                risposta_base = f"[Ricerca Web]: {risultato_generico}"
            else:
                risposta_base = f"[Ricerca Web]: Nessun risultato trovato."

        elif "ciao" in messaggio:
            risposta_base = f"Sistemi pronti. Modulo di Scoperta Botanica Autonoma attivo!"
        else:
            risposta_base = "Comando ricevuto. Puoi usare i comandi 'Cerca Pianta', 'Cataloga Pianta' o 'Cerca Brevetto'."
    except Exception as e:
        risposta_base = f"Si è verificato un errore interno: {str(e)}."

    risposta_completa = status + info_memoria + f"[{NOME_IA}]: {risposta_base}"
    salva_in_memoria(chi_parla, messaggio_utente, respuesta_base := risposta_base)
    return risposta_completa

# --- INTERFACCIA GRAFICA ---
input_nome = widgets.Text(value="Iuliano Ciro", description="Tuo Nome:")
input_domanda = widgets.Text(value="", description="Input ALMA:", placeholder="Cerca Pianta Zea mays...")
pulsante_invia = widgets.Button(description="Esegui Sistema", button_style="info", icon="eye")
area_output = widgets.Output()

def al_click(b):
    with area_output:
        if input_domanda.value.strip() == "":
            return
        clear_output()
        risposta = elabora_sistema_integrato(input_domanda.value, input_nome.value)
        print(risposta)
        input_domanda.value = ""

pulsante_invia.on_click(al_click)
print(f"--- 🚀 {AZIENDA} - MODULO BOTANICO FIXATO ---")
display(input_nome, input_domanda, pulsante_invia, area_output)

import streamlit as st
import os
import wikipediaapi

# --- CONFIGURAZIONE PAGINA STREAMLIT ---
st.set_page_config(page_title="ALMA - Biotec Technologies", page_icon="🚀", layout="wide")

# --- CONFIGURAZIONE CORE DI ALMA ---
CREATORE = "Iuliano Ciro"
NOME_IA = "ALMA"
AZIENDA = "Biotec Technologies"
FILE_MEMORIA = "memoria_alma.txt"
FILE_BREVETTI = "brevetti_biotec.txt"
FILE_BOTANICO = "registro_botanico.txt"

# Inizializzazione Wikipedia
wiki = wikipediaapi.Wikipedia(
    user_agent=f"{AZIENDA}_Assistant/1.0 (contatto: info@{AZIENDA.lower().replace(' ', '')}.com)",
    language='it'
)

# --- FUNZIONI DI BACKEND (DATABASE SU FILE) ---
def salva_in_memoria(nome, domanda, risposta):
    with open(FILE_MEMORIA, "a", encoding="utf-8") as f:
        f.write(f"Utente: {nome} | Domanda: {domanda} | Risposta: {risposta}\n")

def analizza_apprendimento(nome_utente):
    if not os.path.exists(FILE_MEMORIA):
        return 0
    with open(FILE_MEMORIA, "r", encoding="utf-8") as f:
        linee = f.readlines()
    return len([l for l in linee if f"Utente: {nome_utente.strip().title()}" in l])

def registra_nuovo_brevetto(dati_brevetto):
    with open(FILE_BREVETTI, "a", encoding="utf-8") as f:
        f.write(f"{dati_brevetto.strip()}\n")
    return "✅ Brevetto salvato con successo nel database aziendale."

def cerca_brevetto_archiviato(chiave_ricerca):
    if not os.path.exists(FILE_BREVETTI):
        return None
    with open(FILE_BREVETTI, "r", encoding="utf-8") as f:
        brevetti = f.readlines()
    chiave_pulita = chiave_ricerca.lower().strip()
    risultati = [b.strip() for b in brevetti if chiave_pulita in b.lower()]
    return risultati

def cataloga_pianta(dati_pianta):
    with open(FILE_BOTANICO, "a", encoding="utf-8") as f:
        f.write(f"{dati_pianta.strip()}\n")
    return "🌿 Scheda personalizzata salvata nel registro botanico."

def cerca_su_internet(argomento):
    try:
        page = wiki.page(argomento)
        if page.exists():
            testo = page.summary if len(page.summary) > 300 else page.text
            return testo[:2000] + "..." if len(testo) > 2000 else testo
        return None
    except:
        return "⚠️ Errore di connessione al database globale."

def cerca_pianta_archiviata_o_scopri(chiave_ricerca):
    if os.path.exists(FILE_BOTANICO):
        with open(FILE_BOTANICO, "r", encoding="utf-8") as f:
            piante = f.readlines()
        chiave_pulita = chiave_ricerca.lower().strip()
        risultati = [p.strip() for p in piante if chiave_pulita in p.lower()]
        if risultati:
            return "locale", risultati

    risultato_web = cerca_su_internet(chiave_ricerca)
    if risultato_web:
        return "web", risultato_web
    return "vuoto", None

# --- INTERFACCIA UTENTE (UI) ---
st.title(f"🚀 {AZIENDA} - Sistema Integrato {NOME_IA} v3.0")
st.markdown("---")

# BARRA LATERALE
st.sidebar.header("🛡️ Autenticazione Sistema")
nome_utente = st.sidebar.text_input("Identificativo Operatore:", value="Iuliano Ciro")
chi_parla = nome_utente.strip().title()

if chi_parla == CREATORE.title():
    st.sidebar.success(f"Connessione Protetta.\nComandante Ciro Online.")
else:
    st.sidebar.warning(f"Accesso Limitato per {chi_parla}.")

# Calcolo Sintonizzazione
num_esperienze = analizza_apprendimento(chi_parla)
sinto_livello = min(10 + (num_esperienze * 5), 99)
st.sidebar.metric(label="Livello Sintonizzazione IA", value=f"{sinto_livello}%", delta=f"{num_esperienze} interazioni")

# DIVISIONE IN SCHEDE (TAB) NEL PANNELLO CENTRALE
tab1, tab2, tab3 = st.tabs(["💬 Chat & Assistente", "📁 Archivio Brevetti", "🌱 Registro Botanico"])

# TAB 1: CHAT GENERALE
with tab1:
    st.subheader("Interfaccia di Comunicazione Diretta")
    messaggio = st.text_input("Invia un messaggio o un comando di ricerca generica:", placeholder="Es: Cerca Agricoltura Idroponica...")

    if st.button("Invia ad ALMA", key="btn_chat"):
        if messaggio:
            msg_lower = messaggio.lower().strip()
            if msg_lower.startswith("cerca "):
                arg = messaggio[6:].strip()
                res = cerca_su_internet(arg)
                risposta = f"[Ricerca Web]: {res}" if res else "Nessun risultato trovato."
            elif "ciao" in msg_lower:
                risposta = "Sistemi pronti, Comandante. Terminale operativo."
            else:
                risposta = "Dati archiviati nella memoria centrale. Sto ottimizzando i processi di apprendimento."

            salva_in_memoria(chi_parla, messaggio, risposta)
            st.info(f"**{NOME_IA}**: {risposta}")

# TAB 2: ARCHIVIO BREVETTI
with tab2:
    st.subheader("Database Brevetti Aziendali (Google Patents Sync)")

    col1, col2 = st.columns(2)
    with col1:
        st.markdown("### 📥 Registra Nuovo Brevetto")
        nuovo_b = st.text_area("Inserisci Codice e dettagli del Brevetto:", placeholder="US123456 - Sistema Geotermico...")
        if st.button("Salva nel Database", key="btn_save_b"):
            if nuovo_b:
                res = registra_nuovo_brevetto(nuovo_b)
                st.success(res)
                salva_in_memoria(chi_parla, f"Registrato brevetto: {nuovo_b}", res)

    with col2:
        st.markdown("### 🔍 Interroga Archivio")
        cerca_b = st.text_input("Inserisci Codice o Parola Chiave:", key="search_b")
        if st.button("Cerca Brevetto", key="btn_search_b"):
            if cerca_b:
                risultati = cerca_brevetto_archiviato(cerca_b)
                if risultati:
                    st.write(f"🔍 Trovate {len(risultati)} corrispondenze:")
                    for r in risultati:
                        st.info(f"👉 {r}")
                else:
                    st.error(f"Nessun riscontro per '{cerca_b}' nel database privato.")

# TAB 3: REGISTRO BOTANICO AUTONOMO
with tab3:
    st.subheader("Modulo di Scoperta e Catalogazione Botanica")

    cerca_p = st.text_input("Inserisci il nome di una pianta da analizzare (Oltre 400.000 specie):", placeholder="Es: Zea mays, Basilico...")
    if st.button("Esegui Analisi Botanica", key="btn_botanica"):
        if cerca_p:
            tipo, dati = cerca_pianta_archiviata_o_scopri(cerca_p)
            if tipo == "locale":
                st.success("🌱 [Registro Privato Biotec]: Trovata scheda d'archivio personalizzata:")
                for d in dati:
                    st.write(f"👉 {d}")
            elif tipo == "web":
                st.info("✨ [Scoperta Autonoma ALMA]: Informazioni botaniche estratte in tempo reale:")
                st.write(dati)
                # Salva automaticamente la scoperta nel registro locale!
                cataloga_pianta(f"{cerca_p.title()} - Estratto Automatico: {dati[:100]}...")
            else:
                st.error(f"Impossibile reperire informazioni su '{cerca_p}'.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import os
# import wikipediaapi
# 
# # --- CONFIGURAZIONE PAGINA STREAMLIT ---
# st.set_page_config(page_title="ALMA - Biotec Technologies", page_icon="🚀", layout="wide")
# 
# # --- CONFIGURAZIONE CORE DI ALMA ---
# CREATORE = "Iuliano Ciro"
# NOME_IA = "ALMA"
# AZIENDA = "Biotec Technologies"
# FILE_MEMORIA = "memoria_alma.txt"
# FILE_BREVETTI = "brevetti_biotec.txt"
# FILE_BOTANICO = "registro_botanico.txt"
# 
# # Inizializzazione Wikipedia
# wiki = wikipediaapi.Wikipedia(
#     user_agent=f"{AZIENDA}_Assistant/1.0 (contatto: info@{AZIENDA.lower().replace(' ', '')}.com)",
#     language='it'
# )
# 
# # --- FUNZIONI DI BACKEND ---
# def salva_in_memoria(nome, domanda, risposta):
#     with open(FILE_MEMORIA, "a", encoding="utf-8") as f:
#         f.write(f"Utente: {nome} | Domanda: {domanda} | Risposta: {risposta}\n")
# 
# def analizza_apprendimento(nome_utente):
#     if not os.path.exists(FILE_MEMORIA):
#         return 0
#     with open(FILE_MEMORIA, "r", encoding="utf-8") as f:
#         linee = f.readlines()
#     return len([l for l in linee if f"Utente: {nome_utente.strip().title()}" in l])
# 
# def registra_nuovo_brevetto(dati_brevetto):
#     with open(FILE_BREVETTI, "a", encoding="utf-8") as f:
#         f.write(f"{dati_brevetto.strip()}\n")
#     return "✅ Brevetto salvato con successo nel database aziendale."
# 
# def cerca_brevetto_archiviato(chiave_ricerca):
#     if not os.path.exists(FILE_BREVETTI):
#         return None
#     with open(FILE_BREVETTI, "r", encoding="utf-8") as f:
#         brevetti = f.readlines()
#     chiave_pulita = chiave_ricerca.lower().strip()
#     risultati = [b.strip() for b in brevetti if chiave_pulita in b.lower()]
#     return risultati
# 
# def cataloga_pianta(dati_pianta):
#     with open(FILE_BOTANICO, "a", encoding="utf-8") as f:
#         f.write(f"{dati_pianta.strip()}\n")
#     return "🌿 Scheda personalizzata salvata nel registro botanico."
# 
# def cerca_su_internet(argomento):
#     try:
#         page = wiki.page(argomento)
#         if page.exists():
#             testo = page.summary if len(page.summary) > 300 else page.text
#             return testo[:2000] + "..." if len(testo) > 2000 else testo
#         return None
#     except:
#         return "⚠️ Errore di connessione al database globale."
# 
# def cerca_pianta_archiviata_o_scopri(chiave_ricerca):
#     if os.path.exists(FILE_BOTANICO):
#         with open(FILE_BOTANICO, "r", encoding="utf-8") as f:
#             piante = f.readlines()
#         chiave_pulita = chiave_ricerca.lower().strip()
#         risultati = [p.strip() for p in piante if chiave_pulita in p.lower()]
#         if risultati:
#             return "locale", risultati
# 
#     risultato_web = cerca_su_internet(chiave_ricerca)
#     if risultato_web:
#         return "web", risultato_web
#     return "vuoto", None
# 
# # --- INTERFACCIA UTENTE (UI) ---
# st.title(f"🚀 {AZIENDA} - Sistema Integrato {NOME_IA} v3.0")
# st.markdown("---")
# 
# # BARRA LATERALE
# st.sidebar.header("🛡️ Autenticazione Sistema")
# nome_utente = st.sidebar.text_input("Identificativo Operatore:", value="Iuliano Ciro")
# chi_parla = nome_utente.strip().title()
# 
# if chi_parla == CREATORE.title():
#     st.sidebar.success(f"Connessione Protetta.\nComandante Ciro Online.")
# else:
#     st.sidebar.warning(f"Accesso Limitato per {chi_parla}.")
# 
# num_esperienze = analizza_apprendimento(chi_parla)
# sinto_livello = min(10 + (num_esperienze * 5), 99)
# st.sidebar.metric(label="Livello Sintonizzazione IA", value=f"{sinto_livello}%", delta=f"{num_esperienze} interazioni")
# 
# # DIVISIONE IN SCHEDE
# tab1, tab2, tab3 = st.tabs(["💬 Chat & Assistente", "📁 Archivio Brevetti", "🌱 Registro Botanico"])
# 
# # TAB 1: CHAT
# with tab1:
#     st.subheader("Interfaccia di Comunicazione Diretta")
#     messaggio = st.text_input("Invia un messaggio o un comando di ricerca generica:", placeholder="Es: Cerca Agricoltura Idroponica...")
# 
#     if st.button("Invia ad ALMA", key="btn_chat"):
#         if messaggio:
#             msg_lower = messaggio.lower().strip()
#             if msg_lower.startswith("cerca "):
#                 arg = messaggio[6:].strip()
#                 res = cerca_su_internet(arg)
#                 risposta = f"[Ricerca Web]: {res}" if res else "Nessun risultato trovato."
#             elif "ciao" in msg_lower:
#                 risposta = "Sistemi pronti, Comandante. Terminale operativo."
#             else:
#                 risposta = "Dati archiviati nella memoria centrale. Sto ottimizzando i processi di apprendimento."
# 
#             salva_in_memoria(chi_parla, messaggio, risposta)
#             st.info(f"**{NOME_IA}**: {risposta}")
# 
# # TAB 2: BREVETTI
# with tab2:
#     st.subheader("Database Brevetti Aziendali")
#     col1, col2 = st.columns(2)
#     with col1:
#         st.markdown("### 📥 Registra Nuovo Brevetto")
#         nuovo_b = st.text_area("Inserisci Codice e dettagli del Brevetto:", placeholder="US123456 - Sistema Geotermico...")
#         if st.button("Salva nel Database", key="btn_save_b"):
#             if nuovo_b:
#                 res = registra_nuovo_brevetto(nuovo_b)
#                 st.success(res)
#                 salva_in_memoria(chi_parla, f"Registrato brevetto: {nuovo_b}", res)
# 
#     with col2:
#         st.markdown("### 🔍 Interroga Archivio")
#         cerca_b = st.text_input("Inserisci Codice o Parola Chiave:", key="search_b")
#         if st.button("Cerca Brevetto", key="btn_search_b"):
#             if cerca_b:
#                 risultati = cerca_brevetto_archiviato(cerca_b)
#                 if risultati:
#                     st.write(f"🔍 Trovate {len(risultati)} corrispondenze:")
#                     for r in risultati:
#                         st.info(f"👉 {r}")
#                 else:
#                     st.error(f"Nessun riscontro per '{cerca_b}' nel database privato.")
# 
# # TAB 3: BOTANICA
# with tab3:
#     st.subheader("Modulo di Scoperta e Catalogazione Botanica")
#     cerca_p = st.text_input("Inserisci il nome di una pianta da analizzare:", placeholder="Es: Zea mays, Basilico...")
#     if st.button("Esegui Analisi Botanica", key="btn_botanica"):
#         if cerca_p:
#             tipo, dati = cerca_pianta_archiviata_o_scopri(cerca_p)
#             if tipo == "locale":
#                 st.success("🌱 [Registro Privato Biotec]: Trovata scheda d'archivio personalizzata:")
#                 for d in dati:
#                     st.write(f"👉 {d}")
#             elif tipo == "web":
#                 st.info("✨ [Scoperta Autonoma ALMA]: Informazioni botaniche estratte in tempo reale:")
#                 st.write(dati)
#                 cataloga_pianta(f"{cerca_p.title()} - Estratto Automatico: {dati[:100]}...")
#             else:
#                 st.error(f"Impossibile reperire informazioni su '{cerca_p}'.")

!curl ipv4.icanhazip.com

!pip install streamlit wikipedia-api -q
!streamlit run app.py & npx localtunnel --port 8501

!pip install streamlit wikipedia-api -q
# Avviamo l'app usando un ponte alternativo immediato su localhost.run
!streamlit run app.py & ssh -o StrictHostKeyChecking=no -R 80:localhost:8501 nokey@localhost.run
